server:
  port: 8081

joinfaces:
  primefaces:
    theme: saga

  faces:
    project-stage: development

spring:
  application:
    name: 'World Cup api'
  datasource:
    url: jdbc:h2:mem:worldcupdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
app:
  world-cups:
    banners-path: '/worldcups_banners'

  players:
    players-image: '/players_image'

  data:
    world-cups-path: './data/WorldCups.csv'
    world-cups-matches-path: './data/WorldCupMatches.csv'
    world-cups-players-path: './data/WorldCupPlayers.csv'

  resource:
    server-side-pattern-path: '/storage/**'
    storage:
      path: 'D:/storage'

