server:
  port: ${APP_PORT:-8091}

joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: ${FACES_PROJECT_STAGE:-development}

spring:
  application:
    name: 'World Cup api'

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/worldcupdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  world-cups:
    banners-path: '${APP_WORLDCUPS_BANNERS_PATH:-/worldcups_banners}'

  players:
    players-image: '${APP_PLAYERS_IMAGE_PATH:-/players_image}'

  data:
    world-cups-path: '${APP_DATA_WORLDCUPS_PATH:-./app/data/WorldCups.csv}'
    world-cups-matches-path: '${APP_DATA_MATCHES_PATH:-./app/data/WorldCupMatches.csv}'
    world-cups-players-path: '${APP_DATA_PLAYERS_PATH:-./app/data/WorldCupPlayers.csv}'

  resource:
    server-side-pattern-path: '/storage/**'
    storage:
      path: '${APP_STORAGE_PATH:/app/storage}'

  backoffice:
    username: "${APP_BACKOFFICE_USERNAME:admin}"
    password: "${APP_BACKOFFICE_PASSWORD:123}"